### ISSUE TITLE
Review the AzureGateway preliminary description in OPC-UA-OOI

### ISSUE THREAD

**Issue by mpostol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#20]
Current description is in Readme.md file:

[Azure Gateway DataRepository Implementation](https://github.com/mpostol/OPC-UA-OOI/tree/master/Networking/DataRepository/AzureGateway#azure-gateway-datarepository-implementation)

Fork and PR if any modifications are required. Close if the description is fine for now.

**Comment by Drutol** [comment]
I wonder about including info on which part of Azure this implementation is communicating with. Saying just  `Azure` is quite broad, adding note on IoT Hub/IoT Central may be benefitial to the reader.

**Comment by mpostol** [comment]
@Drutol, Good point. I agree but I have decided to make progress on the article first to have more text to rollout to this readme. We should also wait for the feedback from Microsoft to make sure that our proposal is harmonized with the official approach. 
I think it is worth adding a new issue addressing this topic.  What do you think?

**Comment by Drutol** [comment]
I guess that's for the best since this issue is just for review.

**Comment by mpostol** [comment]
Yes, you may close it if done.

**Comment by mpostol** [comment]
I assume it is done for now.
