### ISSUE TITLE
Describe Azure Services

### ISSUE THREAD

**Issue by mpostol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#3]
## Functionality

- [IoT Central](https://docs.microsoft.com/en-gb/azure/iot-central/core/)
- [Azure IoT Hub](https://docs.microsoft.com/en-us/azure/iot-hub/)
- [Azure Industrial IoT Platform](https://github.com/Azure/Industrial-IoT#azure-industrial-iot-platform)
- Azure Event Hubs, 
- Azure ServiceBus, 
- Azure Blob storage

## Decision

- What we have selected
- Why

**Comment by Drutol** [comment]
It may be worth checking out [Event Grid](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid) too

**Comment by mpostol** [comment]
@Drutol 
- add the proposed topic to the main description
- add URL to existing ones

**Comment by Drutol** [comment]
## General services

### [Iot Central](https://azure.microsoft.com/en-us/services/iot-central/)
- provides device types
- provides visualization mechanisms

### [Azure IoT Hub](https://docs.microsoft.com/en-us/azure/iot-hub/)
- part of IoT Central
- provides robust messaging solution, with responses/acknowledgements and commands
- operates without types allowing any devices to exchange any kind of data
- provides device identity
- supports AMQP, MQTT, HTTPS
- max message can be 256kb max

### [Industrial IoT](https://github.com/Azure/Industrial-IoT)
- complex solution targetting various IIoT protocols 
- runs based on [Azure IoT Edge](https://azure.microsoft.com/en-in/services/iot-edge/)
- appears to be focused on client-server aspect of OPCUA

### [Azure IoT Edge](https://azure.microsoft.com/en-in/services/iot-edge/)
- service that allows extracting initial data processing to local premises
- helps saving the bandwidth thanks to sending the results of local processing
- provides separate Virtual Machine images for Azure supported runtime
- end users appear to be developing [modules](https://docs.microsoft.com/en-us/azure/iot-edge/module-development) which target aforementioned runtime to communicate with actual Azure and process the data

### [Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/)
- like AWS S3
- meant to store blobs of static data
- various tiers of storage (Hot&Cold)
- allows to define data lifetime
- enables public access to the data
- via SAS tokens it allows to delegate data upload directly by the client eliminating the need to forward it through some other infrastructure
- required by IoT Hub if messages are to contain data over 256kb

###  [Digital Twins](https://azure.microsoft.com/en-us/services/digital-twins/)
- currently developed tech
- aims to manage the graph of digital twins which is to represent some real world process or entity
- works based on DTDL v2
- allows data ingress and egress 
- graph traversing, mangement, versioning
- can forward data to the messaging services described below

## Messaging services

Comparison can be found [here](https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services).

event - fire and forget, sender does not particularly care about what will happen with this piece of data
message - contract exists between sender are recipient, sender expects recipient to process the message in certain way

### [Event Grid](https://docs.microsoft.com/en-us/azure/event-grid/)
- notification events, but not bulk sensor data
- promotes reactive programming
- main purpose is to react to status changes

### [Event Hubs](https://docs.microsoft.com/en-us/azure/event-hubs/)
- notification events, big data streams
- focused on telemetry purposes

### [Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/)
- robust messaging for enterprise applications
- supports transations, ordering, duplicates removal, provides delivery guarantees

**Comment by mpostol** [comment]
- `Azure IoT Hub` - the wrong link - it opens general documentation,
- [What is Azure Blob storage?](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-overview) - I propose this
- [Azure Digital Twins Preview Documentation](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-overview) - consider this

@Drutol  - after finishing return it back to me.

**Comment by Drutol** [comment]
Not sure what's wrong with blob storage, just different link?
Your Digital Twins link refers to blob storage.

**Comment by mpostol** [comment]
OK, I will take it and convert it to a markdown document.

**Comment by Drutol** [comment]
I believe you could edit/copy my comment if anything for markdown.

**Comment by Drutol** [comment]
https://wikiazure.com/wp-content/uploads/2016/12/Microsoft_Azure_IoT_Reference_Architecture-1.pdf

Found a bit dated but maybe revelant reference for Azure IoT architecture. They mention OPCUA there too.

**Comment by Drutol** [comment]
As for "Messaging Services" group, I agree, they are pretty much out of scope.

**Comment by mpostol** [comment]
> https://wikiazure.com/wp-content/uploads/2016/12/Microsoft_Azure_IoT_Reference_Architecture-1.pdf
> 
> Found a bit dated but maybe revelant reference for Azure IoT architecture. They mention OPCUA there too.

There is new external data source (role) defined as Field Gateway.  It could be considered in #9
