### ISSUE TITLE
Find reference for real-time systems

### ISSUE THREAD

**Issue by Drutol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#33]
Needs to find proper reference defining the real-time systems.

**Comment by mpostol** [comment]
Not sure what I wrote in [Real-Time Communication for Large Scale Distributed Control Systems](https://www.researchgate.net/publication/338595754_Real-Time_Communication_for_Large_Scale_Distributed_Control_Systems ). 
Anyway, it looks like a good starting point for further research.

**Comment by mpostol** [comment]
Reviewed the above-mentioned paper.
