### ISSUE TITLE
Research on publication journal

### ISSUE THREAD

**Issue by mpostol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#50]
Consider publishing in:

- [IEEE Transactions on Industrial Informatics](https://ieeexplore.ieee.org/xpl/aboutJournal.jsp?punumber=9424)
- [IEEE Transactions on Software Engineering](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=32)
- [INTERNATIONAL CONFERENCE ON COMPUTATIONAL SCIENCE](https://www.iccs-meeting.org/iccs2021/call-for-papers/)
- [Journal of Applied Computer Science](https://it.p.lodz.pl/course/view.php?id=12)

**Comment by mpostol** [comment]
@Drutol - consider publication: INTERNATIONAL CONFERENCE ON COMPUTATIONAL SCIENCE (ICCS2021)

1. [Topics](https://www.iccs-meeting.org/iccs2021/call-for-papers/)
   - Parallel and Distributed Computing
   - Advanced Computing Architectures and New Programming Models
1. [Tracks](https://www.iccs-meeting.org/iccs2021/thematic-tracks/)
   - [Computational Science in IoT and Smart Systems – IoTSS](https://www.iccs-meeting.org/iccs2021/thematic-tracks/#ws7)
   - [Software Engineering for Computational Science – SE4Science](http://www.cs.emory.edu/~vss/iotss2021/)

**Comment by Drutol** [comment]
Sounds good!

**Comment by mpostol** [comment]
Next step:
- INTERNATIONAL CONFERENCE ON COMPUTATIONAL SCIENCE
