### ISSUE TITLE
Prepare the article scope and template

### ISSUE THREAD

**Issue by mpostol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#7]
- [x] update the Readme.md
- [x] create master document containing all relevant sections in markdown

**Comment by mpostol** [comment]
@Drutol review the document README.md and pass the issue back to me.

**Comment by Drutol** [comment]
Hmm, about the "Metadata" part of "Azure Main Technology ~~Fetuses~~ Features". Not sure if the order is optimal.

Wouldn't it be better to first describe _DTDL_ and later the _Device Template_ so that reader is familiar with the matter? Or is it better to state the problem first in_Device Template_ and then proceed with solution that _DTDL_ offers? 

Also both Device _Capability Model_ and _Interface_ are parts of the _DTDL _ itself so I think they should be contained within the DTDL section.

**Comment by Drutol** [comment]
> Simple, complex and structural data processing

How do you perceive the difference between complex & structural? Complex as in for example geopostion and structural as in objects with simple and complex data? 
As per [DTDL docs](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v1-preview/dtdlv1.md#schemas) it describes possible structured data as "complex" alongside Dictionaries, Arrays and enums.

**Comment by Drutol** [comment]
> Azure to Sensors (M2S) 

(not sure what M2S stands for here)
Sounds like it implies sending commands from the Azure to the Sensors... which is supported by the IoT Central but it's not possible on the PubSub level.

**Comment by Drutol** [comment]
Deployment phases:

> Device/Service association
> Device/Application association
> Establishing session

Honestly I'm getting an impression that it's a bit like the discussed network prorocol analysis. It's being done behind the scenes by the Azure's black box. All we have is SDK which handles establishing the secure communication channel and then with the other thing we have which is either SAS/X.509 which provides:
* Identity of the device 
* Authorization for specified resources

So unless there's a greater scheme behind these I missed it'd all be just "Establishing connection context". Unless you mean mixed flow of Azure configuration interweaved with actual device in runtime?

> Establishing a semantic-context

We are not directly establishing semantic context, the message properties are mapped after they surface from IoT Hub to IoT Central (if such template is assigned) somewhere in the cloud. From the device perspective its identity is the context. Also it is under the "Establishing session" part but semantic context is defined before the session starts being established... assuming session means active connection here.

> Security management - establishing security-context
> Authentication

Aren't these the same thing in this IoT Hub's context?

**Comment by mpostol** [comment]
Next steps:

- [x] review and discuss the reported comments
- [x] prepare the master document or documents
- [ ] start review procedure

**Comment by mpostol** [comment]
> Hmm, about the "Metadata" part of "Azure Main Technology ~Fetuses~ Features". Not sure if the order is optimal.
> 
> Wouldn't it be better to first describe _DTDL_ and later the _Device Template_ so that reader is familiar with the matter? Or is it better to state the problem first in_Device Template_ and then proceed with solution that _DTDL_ offers?
> 
> Also both Device _Capability Model_ and _Interface_ are parts of the _DTDL _ itself so I think they should be contained within the DTDL section.

Final discussion and decisions moved to the new issue #13
